name: Lint VBA

on:
  push:
    branches:
      - main
      - dev
  pull_request:
jobs:
  test-and-static-analysis:
    name: Test and Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      uses: DecimalTurn/lint-vba@main # This action should point to the dev version of the GitHub action
      with:
        path: './src'
