name: Lint VBA

on:
  push:
    branches:
      - dev
  pull_request:
jobs:
  test-and-static-analysis:
    name: Test and Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      uses: Vba-actions/lint-vba@main
      with:
        path: './src'
